### ISSUE TITLE
How to Make it work with Aws lambda

### ISSUE THREAD

**Issue by Deku-izuku-dotcom** [DevSecOpsDocs/nuclearpond#1]
Hello 

I read the Blog & some resource but i didn't get the idea , how to make nuclear pond work With AWS lambda ? 

Best Regards

**Comment by jonathanwalker** [comment]
So this is just the client and you need to setup the backend. To get it to work with lambda you need to deploy these resources using terraform. Clone this repository, run terraform apply, and set the lambda function name that was deployed in this utility. Feel free to let me know if you have any issues.

https://github.com/DevSecOpsDocs/terraform-nuclear-pond
