### ISSUE TITLE
When running "everything" it is extremely likely that you will run into a 15 min max lambda lifespan and timeout.

### ISSUE THREAD

**Issue by S4lt5** [DevSecOpsDocs/nuclearpond#2]
What is the best practices way to stripe jobs across so that I can run smaller chunks of "all" templates, while still making sure that I  have a good "catch all" routine that won't be broken by later template updates?

The examples all show "-t dns", but for example if I were to use "-t http" it will fail because I need to also specify a subdirectory within http.

What is the best way to run "all of the templates" but avoid lambda timeouts?

**Comment by jonathanwalker** [comment]
The best way to run a large amount of templates at once would be specify rate limit and concurrency configurations flags nuclei provides. I hint at that in the basic scan in the blog post.

https://devsecopsdocs.com/blog/nuclear-pond/#basic-scan

As for the specifying a specific subdirectory, you may need to elaborate further. Perhaps review nuclei documentation for more potential approaches you can take for doing so. If you want more information about using custom templates, please review the infrastructure repository.

**Comment by S4lt5** [comment]
To clarify, I was initially hoping to do a "no args" run where it just runs everything that doesn't need special inputs, but that exceeds the 15 minute lambda timeout frequently enough to make it infeasible.

I currently broke out each template subdirectory into its own job, but then the runtime across all of the jobs (due to the global aws concurrency limit) is actually not too great.

I spent some time thinking about this and I think I'm going to try to break it up into two different jobs that cover almost everything I need and use from the existing "classic" way of running nuclei


* All templates that are med/high/critical
* And then another bucket of all the panel exposures, tech detect, etc that I care about all lumped into job 2

I think that will get me what I want and still be quite performant. I am messing with concurrency but really we're trying to run up to the burst lambda limit as much as possible to get these done rapidly.

**Comment by S4lt5** [comment]
I'm gonna close this as I've found sufficient ways to run this to avoid the timeout and still get good performance.
The TLDR; is that breaking up 'info/low' into a separate job should be enough across the board.
